//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioValido", Namespace="http://schemas.datacontract.org/2004/07/Autenticacion")]
    public partial class UsuarioValido : object
    {
        
        private string AtributoObjetoField;
        
        private string CorreoField;
        
        private string DepartamentoField;
        
        private bool EncontradoField;
        
        private int IdCentroCostosField;
        
        private string IdEmpleadoField;
        
        private int IdPerfilField;
        
        private int IdPlazaField;
        
        private string IdUsuarioField;
        
        private string MensajeField;
        
        private string NombreUsuarioField;
        
        private string TituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoObjeto
        {
            get
            {
                return this.AtributoObjetoField;
            }
            set
            {
                this.AtributoObjetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Encontrado
        {
            get
            {
                return this.EncontradoField;
            }
            set
            {
                this.EncontradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroCostos
        {
            get
            {
                return this.IdCentroCostosField;
            }
            set
            {
                this.IdCentroCostosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEmpleado
        {
            get
            {
                return this.IdEmpleadoField;
            }
            set
            {
                this.IdEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerfil
        {
            get
            {
                return this.IdPerfilField;
            }
            set
            {
                this.IdPerfilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlaza
        {
            get
            {
                return this.IdPlazaField;
            }
            set
            {
                this.IdPlazaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario
        {
            get
            {
                return this.NombreUsuarioField;
            }
            set
            {
                this.NombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this.TituloField;
            }
            set
            {
                this.TituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioBuscadoDto", Namespace="http://schemas.datacontract.org/2004/07/Autenticacion")]
    public partial class UsuarioBuscadoDto : object
    {
        
        private string AtributoObjetoField;
        
        private string CorreoField;
        
        private string DepartamentoField;
        
        private bool EncontradoField;
        
        private int IdEmpleadoField;
        
        private string IdUsuarioField;
        
        private string MensajeField;
        
        private string NombreUsuarioField;
        
        private string TituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoObjeto
        {
            get
            {
                return this.AtributoObjetoField;
            }
            set
            {
                this.AtributoObjetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Encontrado
        {
            get
            {
                return this.EncontradoField;
            }
            set
            {
                this.EncontradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado
        {
            get
            {
                return this.IdEmpleadoField;
            }
            set
            {
                this.IdEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario
        {
            get
            {
                return this.NombreUsuarioField;
            }
            set
            {
                this.NombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this.TituloField;
            }
            set
            {
                this.TituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosDominioDto", Namespace="http://schemas.datacontract.org/2004/07/Autenticacion")]
    public partial class DatosDominioDto : object
    {
        
        private string AtributoObjetoField;
        
        private string CorreoUsuarioField;
        
        private string DepartamentoField;
        
        private string DominioLDAPField;
        
        private bool ErrorField;
        
        private string IdUsuarioField;
        
        private string MensajeField;
        
        private string NombreUsuarioField;
        
        private string RutaLDAPField;
        
        private AuthenticationService.AccesoDirectorioActivoMensajeDto TipoUsuarioField;
        
        private string TituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoObjeto
        {
            get
            {
                return this.AtributoObjetoField;
            }
            set
            {
                this.AtributoObjetoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoUsuario
        {
            get
            {
                return this.CorreoUsuarioField;
            }
            set
            {
                this.CorreoUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DominioLDAP
        {
            get
            {
                return this.DominioLDAPField;
            }
            set
            {
                this.DominioLDAPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario
        {
            get
            {
                return this.NombreUsuarioField;
            }
            set
            {
                this.NombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaLDAP
        {
            get
            {
                return this.RutaLDAPField;
            }
            set
            {
                this.RutaLDAPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticationService.AccesoDirectorioActivoMensajeDto TipoUsuario
        {
            get
            {
                return this.TipoUsuarioField;
            }
            set
            {
                this.TipoUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this.TituloField;
            }
            set
            {
                this.TituloField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccesoDirectorioActivoMensajeDto", Namespace="http://schemas.datacontract.org/2004/07/Autenticacion")]
    public enum AccesoDirectorioActivoMensajeDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUser = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserWithAccess = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosUsuarioDto", Namespace="http://schemas.datacontract.org/2004/07/Autenticacion")]
    public partial class DatosUsuarioDto : object
    {
        
        private string ApellidoField;
        
        private string CiudadField;
        
        private string CompaniaField;
        
        private string ContenedorNombreField;
        
        private string CorreoField;
        
        private string DepartamentoField;
        
        private bool ErrorField;
        
        private string EstadoField;
        
        private string MensajeField;
        
        private string MensajeExcepcionField;
        
        private string MiembroDeField;
        
        private string NickNameField;
        
        private string NombreField;
        
        private string NombreDistinguidoField;
        
        private string NombreEmpleadoField;
        
        private string NombreMuestraField;
        
        private string OBJECTCATEGORYField;
        
        private int TipoInstanciaField;
        
        private string TituloField;
        
        private bool UsuarioValidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad
        {
            get
            {
                return this.CiudadField;
            }
            set
            {
                this.CiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compania
        {
            get
            {
                return this.CompaniaField;
            }
            set
            {
                this.CompaniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContenedorNombre
        {
            get
            {
                return this.ContenedorNombreField;
            }
            set
            {
                this.ContenedorNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeExcepcion
        {
            get
            {
                return this.MensajeExcepcionField;
            }
            set
            {
                this.MensajeExcepcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiembroDe
        {
            get
            {
                return this.MiembroDeField;
            }
            set
            {
                this.MiembroDeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName
        {
            get
            {
                return this.NickNameField;
            }
            set
            {
                this.NickNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDistinguido
        {
            get
            {
                return this.NombreDistinguidoField;
            }
            set
            {
                this.NombreDistinguidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado
        {
            get
            {
                return this.NombreEmpleadoField;
            }
            set
            {
                this.NombreEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreMuestra
        {
            get
            {
                return this.NombreMuestraField;
            }
            set
            {
                this.NombreMuestraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBJECTCATEGORY
        {
            get
            {
                return this.OBJECTCATEGORYField;
            }
            set
            {
                this.OBJECTCATEGORYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoInstancia
        {
            get
            {
                return this.TipoInstanciaField;
            }
            set
            {
                this.TipoInstanciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this.TituloField;
            }
            set
            {
                this.TituloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsuarioValido
        {
            get
            {
                return this.UsuarioValidoField;
            }
            set
            {
                this.UsuarioValidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.IAutenticacion")]
    public interface IAutenticacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ValidarUsuarioDirectorioActivo", ReplyAction="http://tempuri.org/IAutenticacion/ValidarUsuarioDirectorioActivoResponse")]
        System.Threading.Tasks.Task<AuthenticationService.UsuarioValido> ValidarUsuarioDirectorioActivoAsync(string pUsuario, int pAplicacion, int pModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ValidarUsuarioDirectorioActivoContrasenia", ReplyAction="http://tempuri.org/IAutenticacion/ValidarUsuarioDirectorioActivoContraseniaRespon" +
            "se")]
        System.Threading.Tasks.Task<AuthenticationService.UsuarioValido> ValidarUsuarioDirectorioActivoContraseniaAsync(string NombreUsuario, int IdAplicacion, int IdSubAplicacion, string Contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/BuscarUsuarioDirectorioActivo", ReplyAction="http://tempuri.org/IAutenticacion/BuscarUsuarioDirectorioActivoResponse")]
        System.Threading.Tasks.Task<AuthenticationService.UsuarioBuscadoDto> BuscarUsuarioDirectorioActivoAsync(string NombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ValidarUsuarioDirectorioActivoJson", ReplyAction="http://tempuri.org/IAutenticacion/ValidarUsuarioDirectorioActivoJsonResponse")]
        System.Threading.Tasks.Task<string> ValidarUsuarioDirectorioActivoJsonAsync(string pUsuario, int pAplicacion, int pModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ValidarUsuarioDirectorioActivoContraseniaJson", ReplyAction="http://tempuri.org/IAutenticacion/ValidarUsuarioDirectorioActivoContraseniaJsonRe" +
            "sponse")]
        System.Threading.Tasks.Task<string> ValidarUsuarioDirectorioActivoContraseniaJsonAsync(string NombreUsuario, int IdAplicacion, int IdSubAplicacion, string Contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/BuscarUsuarioDirectorioActivoJson", ReplyAction="http://tempuri.org/IAutenticacion/BuscarUsuarioDirectorioActivoJsonResponse")]
        System.Threading.Tasks.Task<string> BuscarUsuarioDirectorioActivoJsonAsync(string NombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ValidarUsuarioDA", ReplyAction="http://tempuri.org/IAutenticacion/ValidarUsuarioDAResponse")]
        System.Threading.Tasks.Task<AuthenticationService.DatosDominioDto> ValidarUsuarioDAAsync(string NombreUsuario, string Contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ValidarUsuarioBiztalk", ReplyAction="http://tempuri.org/IAutenticacion/ValidarUsuarioBiztalkResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioBiztalkAsync(string usuarioId, string password, string dominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ObtenerDatosCompletosPorUsuario", ReplyAction="http://tempuri.org/IAutenticacion/ObtenerDatosCompletosPorUsuarioResponse")]
        System.Threading.Tasks.Task<AuthenticationService.DatosUsuarioDto> ObtenerDatosCompletosPorUsuarioAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ObtenerDatosCompletosPorCorreo", ReplyAction="http://tempuri.org/IAutenticacion/ObtenerDatosCompletosPorCorreoResponse")]
        System.Threading.Tasks.Task<AuthenticationService.DatosUsuarioDto> ObtenerDatosCompletosPorCorreoAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAutenticacionChannel : AuthenticationService.IAutenticacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AutenticacionClient : System.ServiceModel.ClientBase<AuthenticationService.IAutenticacion>, AuthenticationService.IAutenticacion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AutenticacionClient() : 
                base(AutenticacionClient.GetDefaultBinding(), AutenticacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.httpAutenticacion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionClient(EndpointConfiguration endpointConfiguration) : 
                base(AutenticacionClient.GetBindingForEndpoint(endpointConfiguration), AutenticacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AutenticacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AutenticacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.UsuarioValido> ValidarUsuarioDirectorioActivoAsync(string pUsuario, int pAplicacion, int pModulo)
        {
            return base.Channel.ValidarUsuarioDirectorioActivoAsync(pUsuario, pAplicacion, pModulo);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.UsuarioValido> ValidarUsuarioDirectorioActivoContraseniaAsync(string NombreUsuario, int IdAplicacion, int IdSubAplicacion, string Contrasenia)
        {
            return base.Channel.ValidarUsuarioDirectorioActivoContraseniaAsync(NombreUsuario, IdAplicacion, IdSubAplicacion, Contrasenia);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.UsuarioBuscadoDto> BuscarUsuarioDirectorioActivoAsync(string NombreUsuario)
        {
            return base.Channel.BuscarUsuarioDirectorioActivoAsync(NombreUsuario);
        }
        
        public System.Threading.Tasks.Task<string> ValidarUsuarioDirectorioActivoJsonAsync(string pUsuario, int pAplicacion, int pModulo)
        {
            return base.Channel.ValidarUsuarioDirectorioActivoJsonAsync(pUsuario, pAplicacion, pModulo);
        }
        
        public System.Threading.Tasks.Task<string> ValidarUsuarioDirectorioActivoContraseniaJsonAsync(string NombreUsuario, int IdAplicacion, int IdSubAplicacion, string Contrasenia)
        {
            return base.Channel.ValidarUsuarioDirectorioActivoContraseniaJsonAsync(NombreUsuario, IdAplicacion, IdSubAplicacion, Contrasenia);
        }
        
        public System.Threading.Tasks.Task<string> BuscarUsuarioDirectorioActivoJsonAsync(string NombreUsuario)
        {
            return base.Channel.BuscarUsuarioDirectorioActivoJsonAsync(NombreUsuario);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.DatosDominioDto> ValidarUsuarioDAAsync(string NombreUsuario, string Contrasenia)
        {
            return base.Channel.ValidarUsuarioDAAsync(NombreUsuario, Contrasenia);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioBiztalkAsync(string usuarioId, string password, string dominio)
        {
            return base.Channel.ValidarUsuarioBiztalkAsync(usuarioId, password, dominio);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.DatosUsuarioDto> ObtenerDatosCompletosPorUsuarioAsync(string nombreUsuario)
        {
            return base.Channel.ObtenerDatosCompletosPorUsuarioAsync(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.DatosUsuarioDto> ObtenerDatosCompletosPorCorreoAsync(string correo)
        {
            return base.Channel.ObtenerDatosCompletosPorCorreoAsync(correo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.httpAutenticacion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.httpAutenticacion))
            {
                return new System.ServiceModel.EndpointAddress("http://scdp100143.capome.coop/Autenticacion/Autenticacion.svc/ServicioAutenticaci" +
                        "on");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AutenticacionClient.GetBindingForEndpoint(EndpointConfiguration.httpAutenticacion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AutenticacionClient.GetEndpointAddress(EndpointConfiguration.httpAutenticacion);
        }
        
        public enum EndpointConfiguration
        {
            
            httpAutenticacion,
        }
    }
}
